[2025-06-25T04:10:34.657+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: django_etl_monitor.run_etl_from_django manual__2025-06-24T10:18:05.950531+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-25T04:10:34.662+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
