[2025-06-30T06:42:13.469+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: django_etl_monitor.run_etl_from_django manual__2025-06-30T06:42:12.250945+00:00 [queued]>
[2025-06-30T06:42:13.476+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: django_etl_monitor.run_etl_from_django manual__2025-06-30T06:42:12.250945+00:00 [queued]>
[2025-06-30T06:42:13.478+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-30T06:42:13.490+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): run_etl_from_django> on 2025-06-30 06:42:12.250945+00:00
[2025-06-30T06:42:13.495+0000] {standard_task_runner.py:60} INFO - Started process 60 to run task
[2025-06-30T06:42:13.498+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'django_etl_monitor', 'run_etl_from_django', 'manual__2025-06-30T06:42:12.250945+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/django_etl_monitor.py', '--cfg-path', '/tmp/tmpia5rxix0']
[2025-06-30T06:42:13.500+0000] {standard_task_runner.py:88} INFO - Job 182: Subtask run_etl_from_django
[2025-06-30T06:42:13.578+0000] {task_command.py:423} INFO - Running <TaskInstance: django_etl_monitor.run_etl_from_django manual__2025-06-30T06:42:12.250945+00:00 [running]> on host 1e5276e652c5
[2025-06-30T06:42:13.664+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='django_etl_monitor' AIRFLOW_CTX_TASK_ID='run_etl_from_django' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T06:42:12.250945+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T06:42:12.250945+00:00'
[2025-06-30T06:42:13.665+0000] {logging_mixin.py:188} INFO - [Airflow DAG] Received conf: {'job_id': 106, 'name': 'Filter Load', 'source_table': 'source_data', 'target_table': 'xyz1', 'transformation_rule': '{"nodes": [{"id": "1", "type": "custom", "data": {"label": "source_data", "type": "input"}, "position": {"x": -0.427775029658477, "y": 106.42777502965848}, "width": 201, "height": 42, "selected": true, "positionAbsolute": {"x": -0.427775029658477, "y": 106.42777502965848}, "dragging": false}, {"id": "2", "type": "custom", "data": {"label": "xyz1", "type": "output"}, "position": {"x": 500, "y": 100}, "width": 201, "height": 42, "selected": false, "dragging": false}, {"id": "3", "type": "custom", "data": {"label": "Filter", "type": "filter", "condition": "age>=40"}, "position": {"x": 251.6999505338527, "y": 94.03852888526146}, "width": 201, "height": 70, "selected": false, "positionAbsolute": {"x": 251.6999505338527, "y": 94.03852888526146}, "dragging": false}], "edges": [{"source": "1", "sourceHandle": null, "target": "3", "targetHandle": null, "id": "1-3"}, {"source": "3", "sourceHandle": null, "target": "2", "targetHandle": null, "id": "3-2"}]}'}
[2025-06-30T06:42:13.747+0000] {logging_mixin.py:188} INFO - Pipeline parse error or not a pipeline: name 'job' is not defined
[2025-06-30T06:42:13.748+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/django_etl_monitor.py", line 48, in run_etl_from_conf
    run_etl_job(job)
  File "/opt/airflow/etl_tool/etl_app/etl/etl_executor.py", line 179, in run_etl_job
    df_result = apply_pipeline(df, pipeline['nodes'], pipeline['edges'])
  File "/opt/airflow/etl_tool/etl_app/etl/etl_executor.py", line 161, in apply_pipeline
    log_node_status(job.id, node['id'], node['data']['type'], 'success')
NameError: name 'job' is not defined
[2025-06-30T06:42:13.785+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=django_etl_monitor, task_id=run_etl_from_django, execution_date=20250630T064212, start_date=20250630T064213, end_date=20250630T064213
[2025-06-30T06:42:13.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 182 for task run_etl_from_django (name 'job' is not defined; 60)
[2025-06-30T06:42:13.833+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-30T06:42:13.853+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
